### ISSUE TITLE
Variables not called

### ISSUE THREAD

**Issue by waynieoaks** [sk3pp3r/speedtest2zabbix#1]
Hi 

Firstly, thank you for such a great script. 

I have found a couple of issues when trying to run that have debugged as being caused by the following: 

spd.sh

lines 84 - 90
 `echo "SpeedTest"` replaced with `echo $ZABBIX_HOST`

line 96
`ZABBIX_SERVER_IP_OR_FQDN` replaced with `$ZABBIX_SRV`

After which it seems to be working without issue. 

Many thanks.

**Comment by sk3pp3r** [comment]
> Hi
> 
> Firstly, thank you for such a great script.
> 
> I have found a couple of issues when trying to run that have debugged as being caused by the following:
> 
> spd.sh
> 
> lines 84 - 90
> `echo "SpeedTest"` replaced with `echo $ZABBIX_HOST`
> 
> line 96
> `ZABBIX_SERVER_IP_OR_FQDN` replaced with `$ZABBIX_SRV`
> 
> After which it seems to be working without issue.
> 
> Many thanks.

Hi, You're more than welcome to fork, make a new branch and open a pull request.

GitHub Standard Fork & Pull Request Workflow
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by waynieoaks** [comment]
Hi

Thank you - I have (hopefully) done that correctly.
